import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { inventory } from '../data/inventory.js'
import Nav from '../components/nav'
import ProductImg from '../components/products'
import Colours from '../components/colours'
import { useState } from 'react'

export default function Home() {

  const [data, setData] = useState([...inventory.clothing]);

  const [filter, setFilter] = useState("Null");
  const [category, setCategory] = useState("Null")


  const changeFilter = (changeFil) => {
    if (changeFil == "male") {
      setFilter("Male");
    } else if (changeFil == "female") {
      setFilter("Female");
    } else if (changeFil == "unisex") {
      setFilter("Unisex");
    }
  }

  const changeCategory = (changeCat) => {
    if (changeCat == "hoodies") {
      setCategory("Hoodies");
    } else if (changeCat == "jackets") {
      setCategory("Jackets");
    } else if (changeCat == "headgear") {
      setCategory("Headgear");
    } else if (changeCat == "null") {
      setCategory("Null");
    }
  }


  return (
    <>
      <Head>
        <title>Geared Up Online Store | BCITSA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <link rel="icon" href="/favicons/favicon.ico" />
      </Head>
      <nav className={styles.nav}>
        <Nav />
      </nav>

      <main className={styles.main}>
        <div className={styles.filterContainer}>
          <h3>Filter By</h3>
          <ul className={styles.filter}>
            <li >
              <h1 onClick={() => changeCategory("null") + changeFilter("male")} className={styles.maleTag}>Male</h1>
              <ul className={styles.male}>
                <li onClick={() => changeCategory("hoodies") + changeFilter("male")}>Hoodies</li>
                <li onClick={() => changeCategory("jackets") + changeFilter("male")}>Jackets</li>
                <li onClick={() => changeCategory("headgear") + changeFilter("male")}>Headgear</li>
              </ul>
            </li>
            <li>
              <h1 onClick={() => changeCategory("null") + changeFilter("female")} className={styles.femaleTag}>Female</h1>
              <ul className={styles.female}>
                <li onClick={() => changeCategory("hoodies") + changeFilter("female")}>Hoodies</li>
                <li onClick={() => changeCategory("jackets") + changeFilter("female")}>Jackets</li>
                <li onClick={() => changeCategory("headgear") + changeFilter("female")}>Headgear</li>
              </ul>
            </li>
            <li>
              <h1 onClick={() => changeCategory("null") + changeFilter("unisex")} className={styles.unisexTag}>Unisex</h1>
              <ul className={styles.unisex}>
                <li onClick={() => changeCategory("hoodies") + changeFilter("unisex")}>Hoodies</li>
                <li onClick={() => changeCategory("jackets") + changeFilter("unisex")}>Jackets</li>
                <li onClick={() => changeCategory("headgear") + changeFilter("unisex")}>Headgear</li>
              </ul>
            </li>
          </ul>
        </div>
        <div className={styles.products}>
          {data && data.map((info, index) => {
            if (info.sex === filter && info.category === category) {
              return (
                <div>
                  <ProductImg
                    key={index}
                    img={info.image}
                  />
                  <div className={styles.info}>
                    <div className={styles.titleCard}>
                      {info.title}
                    </div>
                    <div className={styles.colours}>
                      {info.cost}
                      {info.hex && info.hex.map((colour, ind) => {
                        return (
                          <div>
                            <Colours
                              key={ind}
                              colours={colour}
                            />
                          </div>
                        )
                      })}
                    </div>
                  </div>
                </div>

              )
            } else if (info.sex === filter && category === "Null") {
              return (
                <div >
                  <ProductImg
                    key={index}
                    img={info.image}
                  />
                  <div className={styles.info}>
                    <div className={styles.titleCard}>
                      {info.title}
                    </div>
                  </div>
                </div>
              )
            }
          })}
        </div>
      </main>
    </>
  )
}
