import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { inventory } from '../data/inventory.js'
import ProductImg from '../components/products'
import Colours from '../components/Colours'
import { useState, useEffect } from 'react'

export default function Home() {

  const [data, setData] = useState([...inventory.clothing]);

  const [filter, setFilter] = useState("none");
  const [category, setCategory] = useState("none")


  const changeFilter = (changeFil) => {
    if (changeFil == "male") {
      setFilter("Male");
    } else if (changeFil == "female") {
      setFilter("Female");
    } else if (changeFil == "unisex") {
      setFilter("Unisex");
    }
  }

  const changeCategory = (changeCat) => {
    if (changeCat == "hoodies") {
      setCategory("Hoodies");
    } else if (changeCat == "jackets") {
      setCategory("Jackets");
    } else if (changeCat == "headgear") {
      setCategory("Headgear");
    } else if (changeCat == "none") {
      setCategory("none");
    }
  }


  return (
    <>
      <Head>
        <title>Geared Up Online Store | BCITSA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon(1)/favicon.ico" />
      </Head>
      <nav className={styles.nav}>
        <Image
          className={styles.logo}
          src="/logo/logo.png"
          alt="/logo/logo.png"
          width={200}
          height={100} />
      </nav>

      <main className={styles.main}>
        <div className={styles.filterContainer}>
          <h3>Filter By</h3>
          <ul className={styles.filter}>
            <li >
              <h1 onClick={() => changeCategory("none") + changeFilter("male")} className={styles.maleTag}>Male</h1>
              <ul className={styles.male}>
                <li onClick={() => changeCategory("hoodies") + changeFilter("male")}>Hoodies</li>
                <li onClick={() => changeCategory("jackets") + changeFilter("male")}>Jackets</li>
                <li onClick={() => changeCategory("headgear") + changeFilter("male")}>Headgear</li>
              </ul>
            </li>
            <li>
              <h1 onClick={() => changeCategory("none") + changeFilter("female")} className={styles.femaleTag}>Female</h1>
              <ul className={styles.female}>
                <li onClick={() => changeCategory("hoodies") + changeFilter("female")}>Hoodies</li>
                <li onClick={() => changeCategory("jackets") + changeFilter("female")}>Jackets</li>
                <li onClick={() => changeCategory("headgear") + changeFilter("female")}>Headgear</li>
              </ul>
            </li>
            <li>
              <h1 onClick={() => changeCategory("none") + changeFilter("unisex")} className={styles.unisexTag}>Unisex</h1>
              <ul className={styles.unisex}>
                <li onClick={() => changeCategory("hoodies") + changeFilter("unisex")}>Hoodies</li>
                <li onClick={() => changeCategory("jackets") + changeFilter("unisex")}>Jackets</li>
                <li onClick={() => changeCategory("headgear") + changeFilter("unisex")}>Headgear</li>
              </ul>
            </li>
          </ul>
        </div>
        <div className={styles.products}>
          {data && data.map((info, index) => {
            if (info.sex === filter && (info.category === category)) {
              return (
                <div>
                  <ProductImg
                    key={index}
                    img={info.image}
                  />
                  <div className={styles.info}>
                    <div className={styles.titleCard}>
                      {info.title}

                    </div>
                    <div className={styles.colours}>
                      {info.cost}
                      {
                        info.hex && info.hex.map((colour, ind) => {
                          return (
                            <div>
                              <Colours
                                key={ind}
                                colours={colour}

                              />
                            </div>

                          )
                        })}
                    </div>
                  </div>

                </div>

              )
            } else if (info.sex === filter && category === "none") {
              return (
                <div >
                  <ProductImg 
                    key={index}
                    img={info.image}
                  />
                  <div className={styles.info}>
                    <div className={styles.titleCard}>
                      {info.title}

                    </div>
                  </div>
                </div>
              )
            }
          })}
        </div>
      </main>
    </>
  )
}
